### ISSUE TITLE
Change this repo to be a jekyll repo

### ISSUE THREAD

**Issue by Bertg** [railsgirls-be/railsgirls_guide#3]
Best is to have this repo be a github-pages/jekyll compatible repository.

This way hosting and publishing will be a lot easier.

**Comment by toch** [comment]
I've jekyllfy the rails guide. It's available in the branch [gh-pages](https://github.com/railsgirls-be/railsgirls_guide/tree/gh-pages).

You can also browse at http://railsgirls-be.github.io/railsgirls_guide/ but it's broken due to the absolute links. I'll fix that later.

Locally, you can test it by running `jekyll serve` into that branch.

If ok for you, we should only work in that branch and remove the master one.

What do you think?

**Comment by toch** [comment]
@oana-sipos @Bertg To avoid ppl to work on the master branch, we should remove it and move on to the GitHub pages branch or we will have confusions.

If you are ok, I can do the necessary to definitively switch to them.

**Comment by oana-sipos** [comment]
@toch +1 to your proposal.

**Comment by toch** [comment]
@oana-sipos @Bertg it's done, only one branch and I've fixed the config, if you browse the layout is now correct http://railsgirls-be.github.io/railsgirls_guide/

**Comment by oana-sipos** [comment]
Looks great, thanks @toch!

On Thu, Apr 30, 2015 at 10:03 AM, Christophe Philemotte <
notifications@github.com> wrote:

> @oana-sipos https://github.com/oana-sipos @Bertg
> https://github.com/Bertg it's done, only one branch and I've fixed the
> config, if you browse the layout is now correct
> http://railsgirls-be.github.io/railsgirls_guide/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/railsgirls-be/railsgirls_guide/issues/3#issuecomment-97699639
> .

## 

Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com
