### ISSUE TITLE
Rework the examples towards something more concrete

### ISSUE THREAD

**Issue by borisrorsvort** [railsgirls-be/railsgirls_guide#36]
Last 2 times I’ve done it, I felt like the participants where a bit frustrated to not have something concrete at the end of the day (And we did finish the 2nd part completely). I know it depends a lot on the starting levels of your group but I’m pretty sure we could rework the examples to be more focussed about that. For instance, we could def build a simple blog by the end of the day.
I think it could improve the motivation to go on after the event.

@wrtsprt @Bertg @oana-sipos @joren  What do you think?

**Comment by wrtsprt** [comment]
Can you clarify the specific frustration of your students? ( I guess not reaching the end and being able to show a working version?) 
 
And I totally agree: as concrete as possible. That's why blog seems such a good domain, it somethings most people can associate with and we have a playing field of possible features we can introduce depending on the skill level. I am honestly surprised looking back at the guide that we didn't do the `rails g scaffold post ` anywhere yet. This was an important point to me. Just looking at the issues #16 seems to be meant to figure this out I think. 

The way I see the big picture: 
* introduce html (static page)
* move into rails show something dynamic (i.e. the languages thing), don't stay too long on more dynamic stuff and quickly move into
* make a real scaffolded controller introducing the blog concept i.e. posts / articles / whatever the name is

**Comment by borisrorsvort** [comment]
Exactly :)

ps: the frustrations were not expressed, just a feeling the examples did not convinced them enough to continue at home.

@wrtsprt  I’m working on the general «pitch» and follow up process to increase post RG members retention, but if you could lead that part (examples rework) that’d be awesome. Don’t hesitate to ping if needed. I’ll try to tackle some of the other tickets as well

**Comment by Bertg** [comment]
I guess putting it online would be cool. Then they can show it off... But that adds" a bit" of complexity

**Comment by borisrorsvort** [comment]
@Bertg it’s part of the advanced guides already. It can be done in the new «live coding» session during the code together as a follow up

**Comment by oana-sipos** [comment]
@borisrorsvort Although I would rather base this decision on their feedback for example, and not on the two girls you have coached, it does seem like a good idea to continue the tutorial with generating a Rails app.
@wrtsprt I am also surprised we didn't include it on our guides, were we thinking that after our guide we can go on using the official Rails Girls one? Cannot remember details... it's been a while.

**Comment by borisrorsvort** [comment]
@oana-sipos 

For the feedback, sure. People are already happy with what we give them (especially since it's free). Though from a pedagogical point of view it would make a lot more sense that the course would end with «some» practical knowledge they can redo and understand at home (like a blog).
From the last times we've done it, the part where we start scaffolding come very late and it's not enough for people to have a grasp of it. Hence my request. One reason is that, for some unknown reasons, the last RG ended around 17h. In the official guide, they advise to end around 19h, which give an additional 2h to finish the tutorial and have that «final product».

I was not there at the time, but from what I understood, people who decided to diverge from the original guide thought that it was weird not to start with the basics (html, css) before plunging in rails. I can agree with that but it has some implications like if not given proper time (the missing 2h), you never get to the interesting bit of building something.

So the takeaways are:

* make rg last untill 19h then party to introduce them to the community and meet everyone.
* refocus the guide towards something they would be proud and exited to have build (easiest for us to plan is a blog)

**Comment by nathanvda** [comment]
I agree, I still have a fundamental problem with the reversal and move-away from starting with rails.  Starting with rails (after some theorethical intro) has imho the advantage that people get something working very quickly, even when not completely understanding what is going on.

Reading the (belgian) rails guide, it is very "purist" not pragmatic imho. I get the impression some people think the scaffolds are a really bad idea, but it is really useful for starters to get something going really quickly and easily, which is the advantage for beginners no? 

Also: why did we move away from the standard rails-girl-guides? (NIH syndrome?)

We have to be realistic: we cannot assume to be learning people web-programming in 1 day, but we can give them the feeling of the satisfaction of getting a small success experience to build something and get something working, which hopefully plants a seed to want to learn more. 

I am not sure ending the day at 19h is really smart, because it is already a long and tiring day.

**Comment by oana-sipos** [comment]
No, it is not NIH syndrome, far from it. After 2-3 editions, we have realized that the Rails Girls guides, although fast, it focuses too much on copy-pasting commands without really understanding much. After the workshop day, girls were confused and not really knew what was the HTML, the CSS or the Ruby / Rails part in all that app. This is how we have thought of starting to teach HTML and CSS first, then slowly add some Ruby and finishing with integrating the page in a Rails app.

Maybe we were too ambitious, but we have thought of giving it a try. This is what we have achieved. I guess it was a trade-off, they didn't get TOO far, but at least got a better understanding of what is what. Just as when using Rails Girls guides, you can say you have an app, but you got nothing.

@borisrorsvort That Rails Girls guides is a suggestion and a sample schedule of how *they* did things. I doubt there is any pedagogue there that suggested to have the workshop until 19. The duration is common sense and based on the available logistics. Staying too long won't make it more efficient, I'm afraid.

**Comment by borisrorsvort** [comment]
@oana-sipos agreed for the schedule though rushing the tuto wont be more effecint either. The pedagogic aspect was only about what to cover and the end goal. That being said, last editions we had almost nobody reaching the end.

There is also an important part at the end that we rarely did: the drinks & chat to share the experience. It often ended abruptly. But that is out of scope of this topic.

If we are to keep this version of the guide, we indeed need to make it better. And since it is supposed to be about rails, I'm  in favor to make them have something tangible at the end.
If the tutorial is well done, they can redo it home even if they copy pasted during the event since they will have had the explanation before.

@wrtsprt was about to make some work about that after we had a chat on slack.

**Comment by wrtsprt** [comment]
Actually rereading the guide after a long pause I totally get what @nathanvda means here. The part two really seems to avoid using scaffolds. But that's what this ticket is about. We should introduce them earlier but somehow keep our big picture flow. 

The pages controller should also be user with `generate controller pages about` to get the action and route automatically and reduce confusion.
