### ISSUE TITLE
we state 'rails server' without any indication where to type that into

### ISSUE THREAD

**Issue by wrtsprt** [railsgirls-be/railsgirls_guide#8]
- maybe we can find a generic way to add to any piece of example code where this should go. make console / text editor (and then also which file) input distinct.

**Comment by djouuuuh** [comment]
I think this is valid for all command lines mentioned in your guide. When you know where to cd to execute an instruction, it's easy. But I saw several times my team mate execute a mv or a cp in the wrong directory and get an error. But it's just a suggestion ofc :-)

**Comment by otagi** [comment]
Maybe `mv` and `cp` are unnecessary at this stage. It adds another thing to learn, without real benefit for what we are focused on (Rails, not Bash). They can use something more familiar (Explorer / Finder) to achieve the same result.

For commands in general, it could be useful to remind what the current folder should be, indeed.

**Comment by djouuuuh** [comment]
Yes, that is what I meant. Just a little indication of the folder for each command. No further explanation. :-)

**Comment by mariusandra** [comment]
Indeed we are focused on teaching Rails, not bash/cmd and thus I don't see the need to do everything in the command prompt. It's much more intuitive for them to move files around in finder/explorer, instead of typing cryptic `mv` commands. Did `mv` even work in Windows or was there something else like `ren`?

What I like to do is to explain to them that the black (or white) terminal box is similar to finder/explorer. In both you are inside one folder and can do actions on the files. In finder/explorer you do the actions by right clicking on the file and selecting what do you want to do. In the terminal you can't click, so you instead type what you want to do. Both share the feature that to do anything with the files you must be in the right place. 

On Windows machines it's always clear in which folder you are in the command prompt. It says `C:\Sites>`. On a Mac/Linux it's not so clear, so I used `pwd` to show that they all start in your home directory.

**Comment by wrtsprt** [comment]
I agree to not use any commands that are not necessary. I will create an extra issue for this. This issue is about clarifying the destination of thing students will have to type (we're not going to get around `rails server`). 

I will make an extra issue for replacing filesystem move commands with a visual alternative. 

https://github.com/brug-be/railsgirls_guide/issues/20
